const data = [
  {
    id: "1",
    address: "123 Lorem Ipsum Drive",
    city: "Richmond",
    state: "VA",
    zip: 23221,
    propertyValue: 100000,
    monthlyRentalIncome: 1000,
    squareFeet: 1500,
    bedrooms: 1,
    bathrooms: 1,
    availableToRent: "Available",
    inWatchlist: false,
    description:
      "Charming Brick Cape,3 Bedrooms, (upstairs bedrooms are two room suites.) 2 full bathrooms, eat-in kitchen, new range, Granite Countertops,   Living room with fireplace and wood burning insert, Dining room, Florida room, attached Garage, new windows, A new roof just installed.  2 storage sheds, Spacious rear walled courtyard with outdoor kitchen. Moulded Concrete walkways, sprinkler system. Convenient to downtown and all services.",
    images: [
      "https://static.onecms.io/wp-content/uploads/sites/37/2016/02/15230656/white-modern-house-curved-patio-archway-c0a4a3b3.jpg",
    ],
    amenities: ["Jogging Area", "Clubhouse Pool"],
    notes: "Peter just wrote a test note.",
  },
  {
    id: "2",
    address: "456 Lorem Ipsum Drive",
    city: "Portland",
    state: "OR",
    zip: 23221,
    propertyValue: 200000,
    monthlyRentalIncome: 1000,
    squareFeet: 1600,
    bedrooms: 2,
    bathrooms: 2,
    availableToRent: "Not Available",
    inWatchlist: false,
    description:
      "RENOVATED HOME with the finishes of modern day conveniences! Get ready to be WOWED! Beautifully designed with touches of elegance in a welcoming & comfortable living setting. NEW Kitchen includes custom cabinets, Stainless appliances, quartz counters, tiled backsplash, island w/ seating & storage, designer tiled floors & access to a screened-in porch! NEW Baths includes tile surround shower/tub & LVT floors. NEW Roof, Windows, Doors, HVAC, Water Heater, Plumbing, Electricity, Light Fixtures - all tied together with its refinished wood floors!",
    images: [
      "https://images.adsttc.com/media/images/5ecd/d4ac/b357/65c6/7300/009d/large_jpg/02C.jpg",
      "https://www.forbes.com/advisor/wp-content/uploads/2021/03/featured-image-kitchen-renovation.jpg",
    ],
    amenities: ["Jogging Area", "Clubhouse Pool", "Tennis Court"],
    notes: "Testing notes.",
  },
  {
    id: "3",
    address: "789 Lorem Ipsum Drive",
    city: "Boulder",
    state: "CO",
    zip: 23221,
    propertyValue: 300000,
    monthlyRentalIncome: 1000,
    squareFeet: 1700,
    bedrooms: 3,
    bathrooms: 3,
    availableToRent: "Available",
    inWatchlist: false,
    description:
      "The Curie floorplan boasts flex space on both the first and second floors. The kitchen features a large island and opens to the family room and breakfast nook. The flex space in the front of the home would make a perfect study, dining area or second living space. The study located in the rear of the home is a wonderful space for a home office or den. The spacious loft area on the second floor offers many possibilities.",
    images: [
      "https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/BH-Oakmont-211-2nd-st-46-6-1624611939.jpg",
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/kitchen-decor-ideas-colorful-light-fixture-1580422708.jpg",
      "https://furnitureurban.com/wp-content/uploads/2019/05/vesper-marble-dining-room-set-a.jpg",
    ],
    amenities: [
      "Jogging Area",
      "Clubhouse Pool",
      "Tennis Court",
      "WiFi Internet",
    ],
    notes: "This is a test note.",
  },
  {
    id: "4",
    address: "100 Lorem Ipsum Drive",
    city: "Washington",
    state: "DC",
    zip: 23221,
    propertyValue: 400000,
    monthlyRentalIncome: 1000,
    squareFeet: 1800,
    bedrooms: 4,
    bathrooms: 4,
    availableToRent: "Not Available",
    inWatchlist: true,
    description:
      "The hardwood floors throughout the first floor will lead you to the remodeled kitchen with it's gorgeous granite counters, Celadon glass Subway tile backsplash, 42-inch Custom solid cherry wood cabinets and soft close drawers! Appliances include GE Profile Advantium Microwave/convection, Oven, Bosch SS dishwasher, GE stainless steel side by side refrigerator, duel stainless steel sink with disposal and 2 pantries! The 13x12 Breakfast room is filled with light from the large bow window that overlooks the completely fenced in back yard, deck and impressive cobblestone patio! This opens to the Family Room with a wood burning f/p! The laundry room is complete with Whirlpool Duet washer/dryer and a laundry chute from the Primary Bedroom! You'll love the primary bedroom and the 16x7 walk in closet! There are 3 additional bedrooms and the walk-up attic is completely floored for storage. A true 2 car garage with work bench, cabinets and massive paved turn around at the rear and Beautiful wrought iron fencing. The Full-finished basement recreation room with convenient full bath leads out to a marvelous backyard planned for entertaining; complete with custom patio.",
    images: [
      "https://imageio.forbes.com/specials-images/imageserve/1026205392/Beautiful-luxury-home-exterior-at-twilight/960x0.jpg",
      "https://www.mydomaine.com/thmb/KDUEgNEX2lmp4xuLQYVq3pixM1E=/1512x1512/smart/filters:no_upscale()/Blue-Bedroom-1brextoncole-e55677e5459841e481f2dacf2e04300c.jpeg",
      "https://imageio.forbes.com/specials-images/imageserve/5ffdfc89a676bc1fa37f33cb/Black-and-white-bathroom-with-deep-tub-and-large-shower-/960x0.jpg",
      "https://www.forbes.com/advisor/wp-content/uploads/2021/03/featured-image-kitchen-renovation.jpg",
    ],
    amenities: [
      "Jogging Area",
      "Clubhouse Pool",
      "Tennis Court",
      "WiFi Internet",
      "Offstreet Parking",
      "Metro Access",
    ],
    notes: "This is another test note.",
  },
];

export default data;
